"""Generate Geist widget fonts from the same Next.js font used by the web app."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

root = Path(__file__).resolve().parents[1]
source = root.parent / "web/public/fonts"
fallback_source = root.parent / "web/public/fonts/Geist-Fallback.ttf"
codes = sorted(set(list(range(0x20, 0x100)) + list(range(0x400, 0x460)) + [0x490, 0x491, 0xB0, 0xB7,
    0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026, 0x20AC]))
parts = ['// Generated by scripts/generate_geist_fonts.py. Geist is licensed under SIL OFL 1.1.\n#include "fonts/geist_fonts.h"\n']
for size, weight in [(10,400),(12,400),(12,600),(14,400),(18,600),(28,700)]:
    name = f"geist_{size}_{weight}"
    font = ImageFont.truetype(str(source / f"Geist-{weight}.ttf"), size)
    fallback = ImageFont.truetype(str(fallback_source), size)
    data, glyphs = [], ["{0}"]
    for code in codes:
        char = chr(code)
        face = fallback if code >= 0x400 else font
        left, top, right, bottom = face.getbbox(char, anchor="ls")
        width, height = right - left, bottom - top
        image = Image.new("L", (width, height))
        ImageDraw.Draw(image).text((-left, -top), char, font=face, fill=255, anchor="ls")
        pixels = [round(value * 15 / 255) for value in image.tobytes()]
        if len(pixels) % 2:
            pixels.append(0)
        glyphs.append(f"{{.bitmap_index={len(data)},.adv_w={round(face.getlength(char)*16)},.box_w={width},.box_h={height},.ofs_x={left},.ofs_y={-bottom}}}")
        data.extend((pixels[i] << 4) | pixels[i+1] for i in range(0, len(pixels), 2))
    parts.append(f"static const uint8_t pixels_{name}[]={{\n" + "\n".join(
        ",".join(str(x) for x in data[i:i+32]) + "," for i in range(0, len(data), 32)) + "\n};")
    parts.append(f"static const lv_font_fmt_txt_glyph_dsc_t glyphs_{name}[]={{\n" + ",\n".join(glyphs) + "\n};")
    parts.append(f"static const uint16_t codes_{name}[]={{" + ",".join(str(code-codes[0]) for code in codes) + "};")
    parts.append(f"""
static const lv_font_fmt_txt_cmap_t cmap_{name}[]={{ {{
 .range_start={codes[0]},.range_length={codes[-1]-codes[0]+1},.glyph_id_start=1,
 .unicode_list=codes_{name},.list_length={len(codes)},.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
}} }};
static lv_font_fmt_txt_dsc_t dsc_{name}={{
 .glyph_bitmap=pixels_{name},.glyph_dsc=glyphs_{name},.cmaps=cmap_{name},.cmap_num=1,.bpp=4
}};
const lv_font_t {name}={{
 .get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,
 .line_height={round(size*1.2)},.base_line={round(size*0.2)},.dsc=&dsc_{name},.fallback=&lv_font_montserrat_14
}};
""")
# Widget control glyphs (media, WLED, timer) at 20px, Font Awesome codepoints.
def raster_icon(draw_fn):
    scale = 4
    icon = Image.new("L", (20 * scale, 20 * scale))
    draw = ImageDraw.Draw(icon)

    def xy(x, y):
        return round(x * 20 / 24 * scale), round(y * 20 / 24 * scale)

    def lw():
        return max(1, round(2 * 20 / 24 * scale))

    draw_fn(draw, xy, lw)
    pixels = [round(value * 15 / 255) for value in icon.resize((20, 20), Image.Resampling.LANCZOS).tobytes()]
    return pixels


def draw_play(draw, xy, lw):
    points = [xy(6, 3), xy(20, 12), xy(6, 21)]
    draw.polygon(points, fill=255)


def draw_pause(draw, xy, lw):
    for left, top, right, bottom in [(6, 4, 10, 20), (14, 4, 18, 20)]:
        draw.rectangle([xy(left, top), xy(right, bottom)], fill=255)


def draw_power(draw, xy, lw):
    draw.arc([xy(5, 6), xy(19, 20)], start=45, end=315, fill=255, width=lw())
    draw.line([xy(12, 3), xy(12, 11)], fill=255, width=lw())


def draw_minus(draw, xy, lw):
    draw.rectangle([xy(4, 11), xy(20, 13)], fill=255)


def draw_plus(draw, xy, lw):
    draw.rectangle([xy(4, 11), xy(20, 13)], fill=255)
    draw.rectangle([xy(11, 4), xy(13, 20)], fill=255)


icon_specs = sorted([
    (0xF011, draw_power),
    (0xF04B, draw_play),
    (0xF04C, draw_pause),
    (0xF067, draw_plus),
    (0xF068, draw_minus),
])
icon_data, icon_glyphs = [], ["{0}"]
for _, draw_fn in icon_specs:
    pixels = raster_icon(draw_fn)
    icon_glyphs.append(f"{{.bitmap_index={len(icon_data)},.adv_w=320,.box_w=20,.box_h=20,.ofs_x=0,.ofs_y=0}}")
    icon_data.extend((pixels[i] << 4) | pixels[i + 1] for i in range(0, len(pixels), 2))
icon_range_start = icon_specs[0][0]
icon_unicode = ",".join(str(code - icon_range_start) for code, _ in icon_specs)
parts.append("static const uint8_t icon_pixels[]={" + ",".join(map(str, icon_data)) + "};")
parts.append("static const lv_font_fmt_txt_glyph_dsc_t icon_glyphs[]={" + ",".join(icon_glyphs) + "};")
parts.append(f"""
static const uint16_t icon_unicode_list[]={{{icon_unicode}}};
static const lv_font_fmt_txt_cmap_t icon_cmap[]={{{{.range_start={icon_range_start},.range_length={icon_specs[-1][0]-icon_range_start+1},.glyph_id_start=1,.unicode_list=icon_unicode_list,.list_length={len(icon_specs)},.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}}}};
static lv_font_fmt_txt_dsc_t icon_dsc={{.glyph_bitmap=icon_pixels,.glyph_dsc=icon_glyphs,.cmaps=icon_cmap,.cmap_num=1,.bpp=4}};
const lv_font_t icons_20={{.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height=20,.base_line=0,.dsc=&icon_dsc}};
""")
output = root / "src/fonts/geist_fonts.c"
output.parent.mkdir(exist_ok=True)
output.write_text("\n".join(parts))
print("Generated shared Geist widget fonts")
