"""Cyrillic extension for LVGL's Montserrat fonts (SIL OFL 1.1).

python3 firmware/scripts/generate_ui_fonts.py (Pillow + installed LVGL sources)
ASCII and control icons fall back to the existing built-in font.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

root = Path(__file__).resolve().parents[1]
source = root / ".pio/libdeps/esp32p4_hw/lvgl/scripts/built_in_font/Montserrat-Medium.ttf"
codes = sorted(list(range(0x400, 0x460)) + [0x490, 0x491, 0xB0, 0xB7,
    0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026, 0x20AC])
parts = ['// Generated by scripts/generate_ui_fonts.py. See include/fonts/OFL.txt.\n#include "fonts/ui_fonts.h"\n']
for size in [12, 14, 28]:
    font = ImageFont.truetype(str(source), size)
    data, glyphs = [], ["{0}"]
    for code in codes:
        char = chr(code)
        left, top, right, bottom = font.getbbox(char, anchor="ls")
        width, height = right - left, bottom - top
        image = Image.new("L", (width, height))
        ImageDraw.Draw(image).text((-left, -top), char, font=font, fill=255, anchor="ls")
        pixels = [round(value * 15 / 255) for value in image.tobytes()]
        if len(pixels) % 2:
            pixels.append(0)
        glyphs.append(f"{{.bitmap_index={len(data)},.adv_w={round(font.getlength(char)*16)},.box_w={width},.box_h={height},.ofs_x={left},.ofs_y={-bottom}}}")
        data.extend((pixels[i] << 4) | pixels[i+1] for i in range(0, len(pixels), 2))
    parts.append(f"static const uint8_t pixels_{size}[]={{\n" + "\n".join(
        ",".join(str(x) for x in data[i:i+32]) + "," for i in range(0, len(data), 32)) + "\n};")
    parts.append(f"static const lv_font_fmt_txt_glyph_dsc_t glyphs_{size}[]={{\n" + ",\n".join(glyphs) + "\n};")
    parts.append(f"static const uint16_t codes_{size}[]={{" + ",".join(str(code-codes[0]) for code in codes) + "};")
    parts.append(f"""
static const lv_font_fmt_txt_cmap_t cmap_{size}[]={{ {{
 .range_start={codes[0]},.range_length={codes[-1]-codes[0]+1},.glyph_id_start=1,
 .unicode_list=codes_{size},.list_length={len(codes)},.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
}} }};
static lv_font_fmt_txt_dsc_t dsc_{size}={{
 .glyph_bitmap=pixels_{size},.glyph_dsc=glyphs_{size},.cmaps=cmap_{size},.cmap_num=1,.bpp=4
}};
const lv_font_t ui_font_{size}={{
 .get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,
 .line_height={round(size*1.2)},.base_line={round(size*0.2)},.dsc=&dsc_{size},.fallback=&lv_font_montserrat_{size}
}};
""")
output = root / "src/fonts/ui_fonts.c"
output.parent.mkdir(exist_ok=True)
output.write_text("\n".join(parts))
print("Generated Cyrillic extensions (including Ukrainian) at 12, 14 and 28px")
