"""Rebuild the scalable 4-bit numeric atlas from LVGL's OFL Montserrat font.

Run after `pio run` installs LVGL: python3 firmware/scripts/generate_digits.py
Requires Pillow. Output is compiled into flash, never the DMA heap.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

root = Path(__file__).resolve().parents[1]
source = root / ".pio/libdeps/esp32p4_hw/lvgl/scripts/built_in_font/Montserrat-Medium.ttf"
font = ImageFont.truetype(str(source), 256)
data, glyphs = [], []
for char in "0123456789":
    left, top, right, bottom = font.getbbox(char)
    width, height = right - left, bottom - top
    image = Image.new("L", (width, height))
    ImageDraw.Draw(image).text((-left, -top), char, font=font, fill=255)
    coverage = [round(value * 15 / 255) for value in image.tobytes()]
    if len(coverage) % 2:
        coverage.append(0)
    glyphs.append(f"  {{{len(data)}, {width}, {height}}},")
    data.extend((coverage[i] << 4) | coverage[i + 1] for i in range(0, len(coverage), 2))
output = root / "include/fonts/digits_256.h"
output.write_text(
    "// Generated by scripts/generate_digits.py. Montserrat: SIL OFL 1.1 (see OFL.txt).\n"
    "#pragma once\n#include <stdint.h>\nnamespace DigitAtlas {\n"
    "struct Glyph { uint32_t offset; uint16_t width, height; };\n"
    "static const Glyph glyphs[] = {\n" + "\n".join(glyphs) + "\n};\n"
    "static const uint8_t pixels[] = {\n" + "\n".join(
        "  " + ",".join(str(x) for x in data[i:i + 32]) + "," for i in range(0, len(data), 32)
    ) + "\n};\n}\n"
)
# Keep the complete OFL.txt license alongside the generated atlas.
assert (output.parent / "OFL.txt").exists(), "The font license must accompany the atlas"
print(f"Generated {len(data)} bytes of numeric glyph coverage")
